### ISSUE TITLE
possibility of adding this script to Homebrew

### ISSUE THREAD

**Issue by rosenbergm** [michaljanocko/trak#1]
hey @michaljanocko,

what a great and simple time tracker! I was wondering if you would consider adding trak to Homebrew.

you see, me, a professional typescript & react soydev who likes his lattes from starbucks with extra shots of tasty syrup has no fucking clue what `$PATH` is.

thanks!

**Comment by michaljanocko** [comment]
You want it, you have it.

`brew install michaljanocko/pilsner/trak`
